@extends('layouts.app')
@section('title','Dashboard quản trị')
@section('bodyClass','admin-layout')
@section('content')
<div class="d-flex justify-content-between align-items-center mb-4"><div><h1 class="section-title">Dashboard quản trị</h1><p class="text-muted mb-0">Tổng quan hoạt động CloudMusic.</p></div><div class="d-flex gap-2"><a class="btn btn-soft" href="{{ route('admin.songs.index',['status'=>'pending']) }}">{{ $stats['pending'] }} bài chờ duyệt</a><a class="btn btn-outline-danger" href="{{ route('admin.reports.index',['status'=>'open']) }}">{{ $stats['reports'] }} báo cáo mở</a></div></div>
<div class="row g-3 mb-4">@foreach([['Người dùng',$stats['users'],'bi-people'],['Nghệ sĩ',$stats['artists'],'bi-mic'],['Bài hát',$stats['songs'],'bi-music-note-beamed'],['Lượt nghe',$stats['plays'],'bi-play-circle']] as $item)<div class="col-6 col-xl-3"><div class="stat-card"><i class="bi {{ $item[2] }} fs-3 text-warning"></i><div class="display-6 fw-bold mt-2">{{ number_format($item[1]) }}</div><div class="text-muted">{{ $item[0] }}</div></div></div>@endforeach</div>
<div class="row g-4"><div class="col-xl-7"><div class="glass-card p-4"><h2 class="h5 fw-bold mb-3">Bài hát nhiều lượt nghe</h2><div class="table-responsive"><table class="table table-dark align-middle"><thead><tr><th>Bài hát</th><th>Nghệ sĩ</th><th>Lượt nghe</th><th>Trạng thái</th></tr></thead><tbody>@foreach($topSongs as $song)<tr><td><a href="{{ route('songs.show',$song) }}">{{ $song->title }}</a></td><td>{{ $song->user->name }}</td><td>{{ number_format($song->play_count) }}</td><td><span class="badge text-bg-{{ $song->status==='published'?'success':'warning' }}">{{ $song->status }}</span></td></tr>@endforeach</tbody></table></div></div></div><div class="col-xl-5"><div class="glass-card p-4"><h2 class="h5 fw-bold mb-3">Thành viên mới</h2>@foreach($recentUsers as $user)<div class="d-flex align-items-center gap-3 py-2 border-bottom border-soft"><span class="avatar">{{ $user->initials }}</span><div class="flex-grow-1"><strong>{{ $user->name }}</strong><small class="d-block text-muted">{{ $user->email }}</small></div><span class="badge text-bg-dark">{{ $user->role }}</span></div>@endforeach</div></div></div>
<div class="glass-card p-4 mt-4"><h2 class="h5 fw-bold mb-3">Lượt nghe 14 ngày gần nhất</h2><div class="d-flex align-items-end gap-2" style="height:180px">@php $max=max(1,(int)$playsByDay->max('total')); @endphp @forelse($playsByDay as $point)<div class="flex-fill text-center"><div class="rounded-top" style="height:{{ max(8,($point->total/$max)*140) }}px;background:linear-gradient(#ff8a3d,#ff5a36)" title="{{ $point->total }} lượt"></div><small class="text-muted d-block mt-2">{{ \Carbon\Carbon::parse($point->day)->format('d/m') }}</small></div>@empty<p class="text-muted">Chưa có dữ liệu lượt nghe.</p>@endforelse</div></div>
@endsection
