@extends('layouts.app')
@section('title',$editing?'Chỉnh sửa bài hát':'Tải bài hát')
@section('content')
<div class="row justify-content-center"><div class="col-xl-9"><div class="d-flex justify-content-between align-items-end mb-4"><div><h1 class="section-title">{{ $editing?'Chỉnh sửa bài hát':'Tải bài hát mới' }}</h1><p class="text-muted mb-0">File âm thanh được lưu trong vùng riêng tư và chỉ phát qua stream controller.</p></div></div>
<form class="glass-card p-4 p-lg-5" method="post" enctype="multipart/form-data" action="{{ $editing?route('songs.update',$song):route('songs.store') }}">@csrf @if($editing)@method('put')@endif
<div class="row g-4"><div class="col-lg-5"><label class="form-label">Ảnh bìa</label><div class="music-cover-wrap mb-3"><img id="coverPreview" src="{{ $song->cover_url }}" class="music-cover"></div><input class="form-control" type="file" name="cover" accept="image/jpeg,image/png,image/webp" onchange="coverPreview.src=URL.createObjectURL(this.files[0])"><div class="form-text text-muted">JPG, PNG, WebP. Tối đa {{ config('music.max_image_mb') }} MB.</div></div>
<div class="col-lg-7"><div class="mb-3"><label class="form-label">Tên bài hát</label><input class="form-control form-control-lg" name="title" value="{{ old('title',$song->title) }}" maxlength="180" required></div>
<div class="mb-3"><label class="form-label">File âm thanh {{ $editing?'(để trống nếu không thay)':'' }}</label><input class="form-control" type="file" name="audio" data-audio-input accept="audio/*" {{ $editing?'':'required' }}><input type="hidden" name="duration_seconds" value="{{ old('duration_seconds',$song->duration_seconds) }}"><div class="form-text text-muted"><span data-audio-duration>@if($song->duration_seconds)Thời lượng hiện tại: {{ $song->formatted_duration }}@endif</span> · MP3/WAV/OGG/M4A/AAC/FLAC, tối đa {{ config('music.max_audio_mb') }} MB.</div></div>
<div class="row g-3"><div class="col-md-6"><label class="form-label">Thể loại</label><select class="form-select" name="genre_id"><option value="">Chưa phân loại</option>@foreach($genres as $genre)<option value="{{ $genre->id }}" @selected(old('genre_id',$song->genre_id)==$genre->id)>{{ $genre->name }}</option>@endforeach</select></div><div class="col-md-6"><label class="form-label">Album</label><select class="form-select" name="album_id"><option value="">Không thuộc album</option>@foreach($albums as $album)<option value="{{ $album->id }}" @selected(old('album_id',$song->album_id)==$album->id)>{{ $album->title }}</option>@endforeach</select></div></div>
<div class="row g-3 mt-0"><div class="col-md-4"><label class="form-label">Số track</label><input class="form-control" type="number" name="track_number" min="1" max="999" value="{{ old('track_number',$song->track_number) }}"></div><div class="col-md-4"><label class="form-label">Ngày phát hành</label><input class="form-control" type="date" name="release_date" value="{{ old('release_date',$song->release_date?->format('Y-m-d')) }}"></div><div class="col-md-4"><label class="form-label">Quyền riêng tư</label><select class="form-select" name="visibility"><option value="public" @selected(old('visibility',$song->visibility)==='public')>Công khai</option><option value="private" @selected(old('visibility',$song->visibility)==='private')>Riêng tư</option></select></div></div>
<div class="mt-3"><label class="form-label">Mô tả</label><textarea class="form-control" name="description" rows="6" maxlength="5000">{{ old('description',$song->description) }}</textarea></div>
<div class="d-flex justify-content-end gap-2 mt-4"><a class="btn btn-soft px-4" href="{{ $editing?route('songs.show',$song):route('songs.mine') }}">Hủy</a><button class="btn btn-accent px-4">{{ $editing?'Lưu thay đổi':'Tải lên' }}</button></div></div></div></form></div></div>
@endsection
