@extends('layouts.app')
@section('title',$song->title)
@section('content')
<div class="glass-card p-4 p-lg-5 mb-4" style="background:linear-gradient(135deg,rgba(255,90,54,.18),rgba(19,23,34,.95))">
    <div class="row g-4 align-items-center">
        <div class="col-md-4 col-xl-3"><div class="music-cover-wrap"><img src="{{ $song->cover_url }}" class="music-cover" alt="{{ $song->title }}"></div></div>
        <div class="col-md-8 col-xl-9"><div class="d-flex flex-wrap gap-2 mb-3"><span class="badge rounded-pill text-bg-dark">{{ $song->genre?->name ?? 'Chưa phân loại' }}</span>@if($song->status!=='published')<span class="badge rounded-pill text-bg-warning">{{ $song->status }}</span>@endif</div>
            <h1 class="display-5 fw-bold mb-2">{{ $song->title }}</h1>
            <a class="d-inline-flex align-items-center gap-2 mb-3" href="{{ route('profiles.show',$song->user->username) }}"><span class="avatar">{{ $song->user->initials }}</span><span><strong class="d-block">{{ $song->user->name }}</strong><small class="text-muted">@if($song->release_date){{ $song->release_date->format('d/m/Y') }}@else{{ $song->created_at->format('d/m/Y') }}@endif</small></span></a>
            <div class="wave-placeholder mb-3"></div>
            <div class="d-flex flex-wrap align-items-center gap-2">
                <button class="btn btn-accent btn-lg px-4" data-play-song data-song='@json($song->toPlayerPayload())'><i class="bi bi-play-fill me-1"></i>Phát bài hát</button>
                @auth<form method="post" action="{{ route('songs.like',$song) }}">@csrf<button class="btn btn-soft btn-lg"><i class="bi bi-heart{{ $liked?'-fill':'' }} me-1"></i>{{ $liked?'Đã thích':'Thích' }}</button></form>
                <div class="dropdown"><button class="btn btn-soft btn-lg dropdown-toggle" data-bs-toggle="dropdown"><i class="bi bi-plus-lg"></i> Playlist</button><ul class="dropdown-menu">@forelse($playlists as $playlist)<li><form method="post" action="{{ route('playlists.songs.add',[$playlist,$song]) }}">@csrf<button class="dropdown-item">{{ $playlist->name }}</button></form></li>@empty<li><a class="dropdown-item" href="{{ route('playlists.create') }}">Tạo playlist mới</a></li>@endforelse</ul></div>
                <button class="btn btn-soft btn-lg" data-bs-toggle="modal" data-bs-target="#reportModal"><i class="bi bi-flag"></i></button>@endauth
                @if(auth()->id()===$song->user_id)<a class="btn btn-soft btn-lg" href="{{ route('songs.edit',$song) }}"><i class="bi bi-pencil"></i></a>@endif
            </div>
            <div class="d-flex flex-wrap gap-4 mt-4 text-muted"><span><i class="bi bi-play-fill"></i> {{ number_format($song->play_count) }} lượt nghe</span><span><i class="bi bi-heart"></i> {{ number_format($song->like_count) }} lượt thích</span><span><i class="bi bi-chat"></i> {{ number_format($song->comment_count) }} bình luận</span><span><i class="bi bi-clock"></i> {{ $song->formatted_duration }}</span></div>
        </div>
    </div>
</div>
<div class="row g-4">
    <div class="col-xl-8"><div class="glass-card p-4 mb-4"><h2 class="h5 fw-bold">Giới thiệu</h2><p class="text-muted mb-0" style="white-space:pre-line">{{ $song->description ?: 'Nghệ sĩ chưa thêm mô tả cho bài hát này.' }}</p></div>
        <div class="glass-card p-4"><h2 class="h5 fw-bold mb-4">Bình luận</h2>@auth<form method="post" action="{{ route('songs.comments.store',$song) }}" class="mb-4">@csrf<div class="d-flex gap-3"><span class="avatar">{{ auth()->user()->initials }}</span><div class="flex-grow-1"><textarea class="form-control" name="content" rows="3" maxlength="1000" placeholder="Viết bình luận..." required></textarea><button class="btn btn-accent btn-sm mt-2 px-3">Đăng bình luận</button></div></div></form>@else<div class="alert alert-dark border-soft">Hãy <a href="{{ route('login') }}">đăng nhập</a> để bình luận.</div>@endauth
            @forelse($song->comments as $comment)<div class="d-flex gap-3 mb-4"><span class="avatar">{{ $comment->user->initials }}</span><div class="flex-grow-1"><div class="d-flex justify-content-between gap-2"><div><strong>{{ $comment->user->name }}</strong><small class="text-muted ms-2">{{ $comment->created_at->diffForHumans() }}</small></div>@auth @if(auth()->id()===$comment->user_id || auth()->user()->isAdmin())<form method="post" action="{{ route('comments.destroy',$comment) }}" data-confirm="Xóa bình luận này?">@csrf @method('delete')<button class="btn btn-sm text-danger"><i class="bi bi-trash"></i></button></form>@endif @endauth</div><p class="mb-2">{{ $comment->content }}</p>
                @foreach($comment->replies as $reply)<div class="border-start border-soft ps-3 mt-3"><strong>{{ $reply->user->name }}</strong><small class="text-muted ms-2">{{ $reply->created_at->diffForHumans() }}</small><p class="mb-0">{{ $reply->content }}</p></div>@endforeach
                @auth<button class="btn btn-link btn-sm p-0 mt-2" data-bs-toggle="collapse" data-bs-target="#reply{{ $comment->id }}">Trả lời</button><div class="collapse mt-2" id="reply{{ $comment->id }}"><form method="post" action="{{ route('songs.comments.store',$song) }}">@csrf<input type="hidden" name="parent_id" value="{{ $comment->id }}"><div class="input-group"><input class="form-control" name="content" maxlength="1000" required><button class="btn btn-accent">Gửi</button></div></form></div>@endauth
            </div></div>@empty<p class="text-muted">Chưa có bình luận nào.</p>@endforelse
        </div>
    </div>
    <div class="col-xl-4"><div class="glass-card p-4"><h2 class="h5 fw-bold mb-3">Có thể bạn thích</h2><div data-song-collection>@foreach($related as $item)<div class="song-row" style="grid-template-columns:52px minmax(0,1fr) auto"><button class="border-0 p-0 bg-transparent position-relative" data-play-song data-song='@json($item->toPlayerPayload())'><img src="{{ $item->cover_url }}" class="song-row-cover"></button><div class="min-w-0"><a class="fw-bold d-block text-truncate" href="{{ route('songs.show',$item) }}">{{ $item->title }}</a><small class="text-muted text-truncate d-block">{{ $item->user->name }}</small></div><small class="text-muted">{{ $item->formatted_duration }}</small></div>@endforeach</div></div></div>
</div>
@auth<div class="modal fade" id="reportModal"><div class="modal-dialog"><form class="modal-content" method="post" action="{{ route('reports.store') }}">@csrf<input type="hidden" name="type" value="song"><input type="hidden" name="id" value="{{ $song->id }}"><div class="modal-header"><h5 class="modal-title">Báo cáo bài hát</h5><button class="btn-close btn-close-white" data-bs-dismiss="modal"></button></div><div class="modal-body"><label class="form-label">Lý do</label><select class="form-select mb-3" name="reason" required><option value="copyright">Vi phạm bản quyền</option><option value="inappropriate">Nội dung không phù hợp</option><option value="spam">Spam</option><option value="harassment">Quấy rối</option><option value="other">Khác</option></select><label class="form-label">Chi tiết</label><textarea class="form-control" name="details" rows="4"></textarea></div><div class="modal-footer"><button class="btn btn-soft" type="button" data-bs-dismiss="modal">Hủy</button><button class="btn btn-danger">Gửi báo cáo</button></div></form></div></div>@endauth
@endsection
